name:                Assignments
version:             0.1.0.0
github:              "monzee/Assignments"
license:             BSD3
author:              "Mon Zafra"
maintainer:          "mz@codeia.ph"
copyright:           "(c)2019 Mon Zafra"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            throw-away

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/monzee/Assignments#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Assignments-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Assignments

tests:
  Assignments-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Assignments
